#!/bin/sh
# /etc/rc.d/rc.supervisord
#
# AUTHOR: Josh Jaques <jjaques@gmail.com>
# MODIFIED-BY: Damian Zareba <damianzrb@zohomail.eu>
#
# Start/stop/restart supervisor in slackware.
#
# Tested on -current as of 2022-11-01
#
# To make Supervisor start automatically at boot, make this
# file executable:  chmod +x /etc/rc.d/rc.supervisord

# Time to wait between stop/start on a restart
SHUTDOWN_TIME=3

# Time to wait after a start before reporting success/fail
STARTUP_TIME=2

# Location of the pid file
PIDFILE=/var/run/supervisord.pid

# Config of supervisor
CONFIG=/etc/supervisor/supervisord.conf

# Daemon to start
DAEMON=/usr/bin/supervisord

supervisord_start()
{
	if [ -f $PIDFILE ]
	then
		rm $PIDFILE
	fi
	$DAEMON -c $CONFIG 
}


supervisord_status()
{
	if [ -n $(pgrep $DAEMON > /dev/null) ] && [ -f $PIDFILE ]
	then
		echo "Running [PID: $(cat $PIDFILE)]"
		return 0
	else
		echo "Not running"
		return 1
	fi
}


supervisord_stop()
{
    kill $(cat $PIDFILE) | pkill $DAEMON
    rm $PIDFILE
}

case "$1" in
  'start')
      echo -n "Starting..."
      supervisord_start
      sleep $STARTUP_TIME
      supervisord_status 
  ;;

  'status')
      supervisord_status
  ;;


  'stop')
      supervisord_status && {
        echo -n "Stopping $(cat $PIDFILE)..."
        supervisord_stop
        sleep $SHUTDOWN_TIME
        supervisord_status && echo "Failed" || echo "Success"
      } || {
        echo "Not Running..."
        exit 1
    }
  ;;

  'restart')
      supervisord_status && { 
        echo -n "Stopping $(cat $PIDFILE)..."
        supervisord_stop
        sleep $SHUTDOWN_TIME
      	echo -n "Starting..."
      	supervisord_start
      	sleep $STARTUP_TIME
      	supervisord_status 
} 
  ;;

  *)
    echo "Usage: $0 {start|stop|restart|status}"
  ;;
esac

